[package]
name = "client"
version.workspace = true
authors.workspace = true
description.workspace = true
edition = "2024"

[dependencies]
websocket = { path = "../websocket" }
tokio = { version = "*", features = ["full"] }
