[package]
name = "common"
version.workspace = true
authors.workspace = true
edition = "2024"

[dependencies]
websocket = { path = "../websocket/" }
serde = { workspace = true }
rmp-serde = { workspace = true }
